### ISSUE TITLE
[Partner Export] Remove react-use and use another one instead

### ISSUE THREAD

**Issue by duongjitera** [Jitera/jitera-rn-ui-library#76]
![Screen Shot 2022-03-25 at 12 09 45](https://user-images.githubusercontent.com/99177620/160058427-c0b4b9b4-c6b0-4a77-bfb1-22fe9289dac5.png)

There are some dependencies on react-use which do not support react-native, so that can not run project right now

**Comment by jefrydco** [comment]
This issue was already fix by #77
